### ISSUE TITLE
FEATURE: Check overview for BadNames

### ISSUE THREAD

**Issue by kellcomnet2** [SenorSmartyPants/jellyfin-plugin-refreshsparse#2]
Add ability to check overview for blank/bad names like you do episode title. I implemented this via hardcoding

`|| _badNameList.Any(en => episode.Overview.Contains(en, StringComparison.CurrentCultureIgnoreCase))`

**Comment by SenorSmartyPants** [comment]
You can check the overview for being empty. Check the `Missing overview` option.

Can you provide some examples of episodes that would have an overview with bad names?

**Comment by kellcomnet2** [comment]
A prime example is Jeopardy, the contestants are listed in the overview but the returning champion is listed as TBD until after the episode airs.
