### ISSUE TITLE
Failing to work after 10.9.0

### ISSUE THREAD

**Issue by clowncracker** [SenorSmartyPants/jellyfin-plugin-refreshsparse#7]
It fails automatically and I get this in the logs:

```[2024-05-12 13:38:35.717 -07:00] [ERR] [41] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.Collections.Generic.IReadOnlyList`1<System.ValueTuple`2<System.String,Jellyfin.Data.Enums.SortOrder>>)'.
   at Jellyfin.Plugin.RefreshSparse.RefreshScheduledTask.GetItems()
   at Jellyfin.Plugin.RefreshSparse.BaseRefreshTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)```

**Comment by sannidhyaroy** [comment]
Hey, I'm running Jellyfin `10.9.2` and the latest version of the plugin still shows up as unsupported.
<img width="298" alt="Screenshot 2024-06-15 at 4 21 19 PM" src="https://github.com/SenorSmartyPants/jellyfin-plugin-refreshsparse/assets/58990408/31cdec9f-ae21-4cbe-b306-7a4f80e29450">


<img width="436" alt="Screenshot 2024-06-15 at 4 21 43 PM" src="https://github.com/SenorSmartyPants/jellyfin-plugin-refreshsparse/assets/58990408/3c67cb92-570f-4b91-806b-01dbfa52f904">
